package literals.enums;

public enum Tables {
	ADDRESSES, BANNED_USERS, HOUSE_SAVINGS, INVESTMENTS, MONTHLY_TOTALS,
	MONTHLY_EXP_CATGR, MONTHLY_TRANSACTIONS, PAY_GRADES, REMINDERS, SAVINGS, SITES, USERS
}
