package literals.enums;

public enum Views {
    ACTIVE_REMINDERS, CURRENT_BALANCE_TODAY, DISMISSED_REMINDERS, EXPENSES_V,
    FUTURE_BALANCE_SUM, FUTURE_REMINDERS, FUTURE_TRANSACTIONS_SUM,
    INCOME_V, SAVINGS_BALANCE, TOTAL_HOUSE_SAVINGS, TRUE_BALANCE, UNPAID_CREDITS_SUM
}
